
# tasks file for apache2

---

- name: uninstall apache2
  apt: name={{ item }} update_cache=yes state=absent
  with_items:
   - apache2
  register: uninstall_message
  tags:
    - delete

- debug:
    var: uninstall_message
  tags:
    - delete

- name: install apache2
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
   - apache2
  register: install_message

- debug:
    var: install_message


- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  tags:
    - copyfiles
  notify:
    - restart apache2

- name: copying index.conf file with owner and permissions
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
  tags:
   - copyfiles
 
- name: create virtual host file
  template: src=virtualhost.conf dest=/etc/apache2/sites-available/{{ domain }}.conf
  tags:
   - copyfiles
  notify:
    - restart apache2

- name: Ansible delete multiple file example
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/apache2/sites-available/{{ domain }}.conf
    - /var/www/html/index.html
  tags:
    - delete

- name: Delete index.html file
  shell: rm -rf /etc/apache2/sites-enabled/rewrite.load
  tags:
   - delete


