---
# vars file for apache2
http_port: 80
domain: example.com
apache_service: apache2
apache_daemon_path: /usr/apache2/bin/
apache_server_root: /etc/apache2/
apache_conf_path: /etc/apache2/conf
APACHE_LOG_DIR: /etc/apache2/logs/


